"""Rebuild local WOFF2 assets from the user's licensed font downloads.

Requires fonttools and brotli. Originals stay untouched; the manifest records
their hashes so subsequent builds can identify changes to the input files.
"""
import argparse
import hashlib
import json
from pathlib import Path
import shutil

from fontTools.ttLib import TTFont
from fontTools import subset

parser = argparse.ArgumentParser()
parser.add_argument('--downloads', type=Path, default=Path.home() / 'Downloads')
args = parser.parse_args()
root = Path(__file__).resolve().parents[1]
assets = root / 'src/assets/fonts'
fonts = [
    ('Anton', 'anton', 'Anton', 'Anton-Regular.ttf', '400'),
    ('Inter', 'inter', 'Inter', 'Inter-VariableFont_opsz,wght.ttf', '100 900'),
    ('Yakuma Kana', 'yakuma-kana', 'NotoSansCJK', 'NotoSansCJKjp-Medium.otf', '500'),
    *[('IBM Plex Mono', 'ibm-plex-mono', 'IBM_Plex_Mono', f'IBMPlexMono-{name}.ttf', weight)
      for name, weight in [('Regular', '400'), ('Medium', '500'), ('SemiBold', '600'), ('Bold', '700')]],
    *[('Gontserrat', 'gontserrat', 'gontserrat (1)', f'Gontserrat-{name}.ttf', weight)
      for name, weight in [('Regular', '400'), ('Medium', '500'), ('SemiBold', '600'), ('Bold', '700'), ('ExtraBold', '800'), ('Black', '900')]],
]
manifest = []
rules = ['/* Generated by scripts/prepare-local-fonts.py. Sources stay intact; delivery uses the Latin website subset. */']
website_unicodes = (
    set(range(0x0020, 0x0180))  # Basic Latin, Latin-1 and Latin Extended A
    | {0x1E9E, 0x2013, 0x2014, 0x2018, 0x2019, 0x201C, 0x201D, 0x201E,
       0x2026, 0x2192, 0x2197, 0x2212}  # Current DE/EN copy and UI symbols
)
for family, directory, source_dir, filename, weight in fonts:
    source = args.downloads / source_dir / filename
    output_dir = assets / directory
    output_dir.mkdir(parents=True, exist_ok=True)
    output = output_dir / (source.stem.replace(',', '-').lower() + '.woff2')
    font = TTFont(source, recalcTimestamp=False)
    options = subset.Options()
    options.name_IDs = ['*']
    subsetter = subset.Subsetter(options=options)
    if family == 'Yakuma Kana':
        subsetter.populate(text='ヤクマ')
    else:
        subsetter.populate(unicodes=website_unicodes)
    subsetter.subset(font)
    if family == 'Yakuma Kana':
        # Give the application-specific subset its own family name.
        for record in font['name'].names:
            if record.nameID in (1, 4, 6, 16):
                record.string = ('YakumaKana' if record.nameID == 6 else 'Yakuma Kana').encode(record.getEncoding())
    font.flavor = 'woff2'
    font.save(output)
    font.close()
    shutil.copyfile(args.downloads / source_dir / 'OFL.txt', output_dir / 'OFL.txt')
    manifest.append({
        'family': family, 'weight': weight, 'source': str(source),
        'sourceSha256': hashlib.sha256(source.read_bytes()).hexdigest(),
        'sourceBytes': source.stat().st_size,
        'output': output.relative_to(root).as_posix(), 'outputBytes': output.stat().st_size,
        'outputSha256': hashlib.sha256(output.read_bytes()).hexdigest(),
        'license': (output_dir / 'OFL.txt').relative_to(root).as_posix(),
        'subset': 'ヤクマ' if family == 'Yakuma Kana' else 'Basic Latin, Latin-1, Latin Extended A and current UI symbols',
    })
    unicode_range = '  unicode-range: U+30AF, U+30DE, U+30E4;' if family == 'Yakuma Kana' else ''
    rules.append(f'''@font-face {{
  font-family: '{family}';
  src: url('../assets/fonts/{directory}/{output.name}') format('woff2');
  font-style: normal;
  font-weight: {weight};
  font-display: swap;
{unicode_range}
}}''')
(root / 'src/styles/fonts.css').write_text('\n\n'.join(rules) + '\n', encoding='utf-8')
manifest_path = root / 'docs/implementation/local-fonts.json'
manifest_path.parent.mkdir(parents=True, exist_ok=True)
manifest_path.write_text(json.dumps(manifest, indent=2) + '\n', encoding='utf-8')
print(f'Generated {len(manifest)} fonts: {sum(item["sourceBytes"] for item in manifest):,} -> {sum(item["outputBytes"] for item in manifest):,} bytes')
